# Copyright (C) 2014 Jan Rusnacko
#
# This copyrighted material is made available to anyone wishing to use,
# modify, copy, or redistribute it subject to the terms and conditions of the
# MIT license.

require 'spec_helper'
require 'helpers/git_helper'
require 'tmpdir'
require 'ruby_util/dir'

describe Xenuti::Repository do
  let(:config) do
    c = Xenuti::Config.from_yaml(File.new(CONFIG_FILEPATH).read)
    # substitute with ORIGIN_REPO generated by git_helper
    c.general.repo = ORIGIN_REPO
    c
  end

  context 'fetch_source' do
    it 'should check out repo to the latest version' do
      Dir.mktmpdir do |tmpdir|
        Xenuti::Repository.fetch_source(config, tmpdir)
        expect(Dir.compare(config.general.repo, tmpdir)).to be_true
        expect(config.general.source).to be_eql(tmpdir)
      end
    end

    it 'should update repo to the latest version' do
      # OUTDATED_REPO is one commit behind ORIGIN_REPO
      Xenuti::Repository.fetch_source(config, OUTDATED_REPO)
      expect(Dir.compare(config.general.repo, OUTDATED_REPO)).to be_true
    end
  end

  context 'clone' do
    it 'should clone to empty directory' do
      Dir.mktmpdir do |tmpdir|
        Xenuti::Repository.clone(ORIGIN_REPO, tmpdir)
        expect(Dir.new(ORIGIN_REPO)).to be_eql(Dir.new(tmpdir))
      end
    end

    it 'should fail when destination is not empty' do
      expect do
        Xenuti::Repository.clone(ORIGIN_REPO, FIXTURES)
      end.to raise_error RuntimeError
    end

    it 'should fail when source is not a git repo' do
      expect do
        Xenuti::Repository.clone('/tmp', FIXTURES)
      end.to raise_error RuntimeError
    end
  end

  context 'update' do
    it 'should update outdated repo' do
      # we are testing this as
      # fetch_source#should update repo to the latest version
    end

    it 'should fail when argument is not a git repo' do
      old_pwd = Dir.pwd
      expect do
        Xenuti::Repository.update('/tmp')
      end.to raise_error RuntimeError
      expect(Dir.pwd).to be_eql(old_pwd) # we stay in the same directory
    end
  end

  context 'git_repo?' do
    it 'should return true when git repo is passed' do
      old_pwd = Dir.pwd
      expect(Xenuti::Repository.git_repo?(ORIGIN_REPO)).to be_true
      expect(Dir.pwd).to be_eql(old_pwd)
    end

    it 'should return false when argument is not a git repo' do
      old_pwd = Dir.pwd
      expect(Xenuti::Repository.git_repo?('/tmp')).to be_false
      expect(Dir.pwd).to be_eql(old_pwd)
    end

    it 'should return false when argument is non-existent dir' do
      expect(Xenuti::Repository.git_repo?('/akjfdjhadkjvc')).to be_false
    end
  end
end
