
AllCops:
  Exclude:
    - 'tmp/**'
    - 'spec/fixtures/**'

Encoding:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

LineLength:
  Max: 80
  Exclude: 
    - 'bin/xenuti'

SpecialGlobalVars:
  Enabled: false

UnusedBlockArgument:
  Exclude:
    - 'bin/xenuti'