
AllCops:
  Exclude:
    - 'tmp/**'
    - 'spec/fixtures/**/*'

Encoding:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

GlobalVars:
  Enabled: false

LineLength:
  Max: 80
  Exclude: 
    - 'bin/xenuti'

ClassLength:
  Max: 150

MethodLength:
  Max: 12

ClassVars:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

UnusedBlockArgument:
  Exclude:
    - 'bin/xenuti'

ConstantName:
  Exclude:
    - 'lib/xenuti/version.rb'